name: release
on:
  push:
    tags:
      # Only run on semver tags, but not prereleases 
      - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cli/gh-extension-precompile@v1
